Repository artsy/img, pull requests merged in 2022-12, with the labels that each got.

#2 ci: sets up ci
  .circleci/config.yml
  .gitignore
  package.json
  yarn.lock
Labels: minor, canary

#3 ci: adds author info via shared autorc
  .autorc
  package.json
  yarn.lock
Labels: patch

#4 ci: adds author
  .autorc
Labels: Version: Patch

#5 Update README.md
  README.md
Labels: canary, Version: Patch

#6 fix: fixes auto config
  .autorc
  package.json
Labels: Version: Patch

#7 feat: optional services
  src/__tests__/services.test.ts
  src/index.ts
  src/services.ts
  src/services/gemini.ts
  src/services/imgix.ts
  src/services/lambda.ts
  src/strategies.ts
Labels: Version: Minor

#8 fix: removes qs dependency; fixes gemini width/height modes
  package.json
  src/__tests__/services.test.ts
  src/services/gemini.ts
  src/services/imgix.ts
  src/utils/stringify.ts
  yarn.lock
Labels: Version: Patch

#9 fix(gemini): fixes crop url mode
  src/__tests__/services.test.ts
  src/services/gemini.ts
Labels: Version: Patch

#10 refactor: renames functions and types to be less generic
  src/__tests__/services.test.ts
  src/services.ts
  src/services/gemini.ts
  src/services/imgix.ts
  src/services/lambda.ts
Labels: Version: Major

#11 fix(lambda): supports url encoded keys
  src/__tests__/services.test.ts
  src/services/lambda.ts
Labels: Version: Patch

#13 fix(lambda): fixes replacement
  src/__tests__/services.test.ts
  src/services/lambda.ts
Labels: Version: Patch
